events {}

http {
    upstream backend {
        server backend:8087;
    }
    upstream frontend_site {
        server frontend-site:0080;
    }
    upstream frontend_admin {
        server frontend-admin:0080;
    }

    server {
        listen 0080;  # frontend-site
        server_name localhost;
        client_max_body_size 50M;

        location /media/ {
            alias /uploads/;
            autoindex on;
            access_log off;
            add_header Cache-Control "public, max-age=31536000";
        }

        # Backend proxy
        location /mingachevir-real-estate-agency/ {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
        }

        # Frontend app
        location / {
            proxy_pass http://frontend_site;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 0081;  # frontend-admin
        server_name localhost;
        client_max_body_size 50M;

        location /media/ {
            alias /uploads/;
            autoindex on;
            access_log off;
        }

        location /mingachevir-real-estate-agency/ {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
        }

        location / {
            proxy_pass http://frontend_admin;
            proxy_set_header Host $host;
        }
    }
}
