spring.application.name=mingachevir-real-estate-server
spring.datasource.url=${POSTGRESQL_DB_URL}
spring.datasource.username=${POSTGRESQL_DB_USERNAME}
spring.datasource.password=${POSTGRESQL_DB_PASSWORD}

server.servlet.context-path=/mingachevir-real-estate-agency
spring.datasource.driver-class-name=org.postgresql.Driver

server.forward-headers-strategy=native
spring.jpa.hibernate.ddl-auto=none

# Disable dev tools
# Secure session cookies
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.properties.hibernate.ejb.entity_manager_factory_interface=jakarta.persistence.EntityManagerFactory

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
spring.flyway.validateMigrationNaming=false

logging.level.org.springframework=DEBUG
logging.level.com.mingachevir=INFO


cloud.r2.endpoint=${R2_ENDPOINT}
cloud.r2.access-key=${R2_ACCESS_KEY}
cloud.r2.secret-key=${R2_SECRET_KEY}
cloud.r2.region=${R2_REGION}
cloud.r2.public-url=${R2_PUBLIC_URL}
application.bucket.name=${R2_BUCKET_NAME}
