events {}

http {
    server {
        listen 0080;
        root /usr/share/nginx/html;
        index index.html index.html;
        etag on;

      location / {
         index index.html;
         try_files $uri /index.html;
         include mime.types;
         default_type application/octet-stream;
       }

        location /uploads/ {
        root /;
        }

    }
}
